# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.menu_like_service:
        class: AppBundle\Services\MenuLikeService
        arguments: ['@doctrine']
    app.twig_extension:
        class: AppBundle\Twig\MenuLikeExtension
        public: false
        arguments: ['@app.menu_like_service']
        tags:
            - { name: twig.extension }
